#!/bin/bash

if [[ $# != 2 ]]
  then
  echo "You are not using the script the way you should"
  echo "Use './data ['host'] ['action']' "
  echo "Possible actions: deleteall getall getindexes getvisualizations getdashboards  'adddashboard name jsonfile' "
  exit
fi

if [[ $2 == "deleteall" ]]
  then
  curl -XDELETE 'http://'$1':9200/*/'

elif [[ $2 == "getall" ]]
  then
  curl -XGET $1':9200/_search' | python -m json.tool

elif [[ $2 == "getindexes" ]]
  then
  curl $1':9200/_cat/indices?v'

elif [[ $2 == "getvisualizations" ]]
  then
  curl -XGET $1':9200/.kibana/visualization/_search?'

elif [[ $2 == "getdashboards" ]]
  then
  curl -XGET $1':9200/.kibana/dashboard/_search?'
fi

elif [[ $2 == "adddashboard" ]]
  then
  curl -XPUT $1':9200/.kibana/dashboard/'$2 -d $3
fi

exit
